### ISSUE TITLE
FOR PROVIDERS PAGE

### ISSUE THREAD

**Issue by defyThemAll** [defyThemAll/neurovascular#1]
- [x] Missing the form download Object. See comp screen shot in slack.
- [x] Please create new template per comp

**Comment by ColmanJoseph** [comment]
This is up on the careers page:
https://neuro.gocortexlabs.com/careers/

short code is like this: 

[download title="Patient Records Release" desc="This is a test form download" file="/wp-content/uploads/sites/3/2017/08/RELEASE-FORM1-.pdf"]

[download title="Title of Doc" desc="Description of Doc" file="/filename"]

**Comment by jasonyost** [comment]
As @ColmanJoseph noted the download object can be added to any page as a shortcode. The template should just be the standard template listed under the templates dropdown, and will work like the other pages.
