### ISSUE TITLE
FOR PROVIDERS SERVICE

### ISSUE THREAD

**Issue by defyThemAll** [defyThemAll/neurovascular#5]
- [ ] If possible, can we hide the FOR PROVIDER'S LOCATION button on that service? Or does that break the service layout?

**Comment by defyThemAll** [comment]
- [ ] If possible, style the FORM as an H5? Perhaps it is...just scaled.

**Comment by ColmanJoseph** [comment]
Hey Ryan, is "For Providers" a Service?

**Comment by ColmanJoseph** [comment]
Hey Ryan, to answer your question, Yes, removing the button will break the Service Layout. So you have a couple of options, leave it as is or make For Providers a page not a Service; however you would not be able to put For Providers in the Service Boxes if you do that.

**Comment by defyThemAll** [comment]
Yep. That's what I was afraid of. 
It's a ux error I should have caught in design. I will see if there's another service we want to feature. We should make For Providers a page.

**Comment by ColmanJoseph** [comment]
Ok,  I made this a page: https://neuro.gocortexlabs.com/for-providers/

**Comment by defyThemAll** [comment]
- [x] Please link button in the Utility nav to page: https://neuro.gocortexlabs.com/for-providers/

**Comment by jasonyost** [comment]
Linked
